name: E2E Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend
      uses: actions/checkout@v4
      with:
        path: frontend # Clones the repo that triggered the action here

    - name: Checkout Backend
      uses: actions/checkout@v4
      with:
        repository: axcvwy/TickNet_backend
        path: backend
        # token: ${{ secrets.GITHUB_PAT }}

    - name: Checkout Selenium Tests
      uses: actions/checkout@v4
      with:
        repository: axcvwy/TickNet_Selenium_tests
        path: e2e-tests
        # token: ${{ secrets.GITHUB_PAT }}


    - name: Setup Java 21 (For Selenium)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Node.js (For Vue.js Frontend)
      uses: actions/setup-node@v4
      with:
        node-version: '20'


    - name: Start Backend
      run: |
        cd backend
        mvn spring-boot:run &
        npx wait-on http://localhost:8080 


    - name: Start Frontend
      run: |
        cd frontend
        npm install
        npm run dev &
        npx wait-on http://localhost:5173


    - name: Run Selenium Tests
      run: |
        cd e2e-tests
        mvn test